name = "PauliPropagation"
uuid = "293282d5-3c99-4fb6-92d0-fd3280a19750"
authors = ["Manuel S. Rudolph"]
version = "0.5.1"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
Bits = "1654ce90-6ed3-553a-957f-9452c3a40996"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlotGraphviz = "78a92bc3-407c-4e2f-aae5-75bb47a6fe36"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
BitIntegers = "0.3"
Bits = "0.2"
JSON = "0.21.4"
PlotGraphviz = "0.6.3"
StatsBase = "0.34"
Test = "1.10"
UUIDs = "1.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"

[targets]
test = ["Yao", "Test"]
